name: sublime-text
adopt-info: sublime-text
summary: A sophisticated text editor for code, markup and prose.
description: |
  A sophisticated text editor for code, markup and prose.

architectures:
  - build-on: i386
  - build-on: amd64

grade: stable
confinement: classic

apps:
  subl:
    command: sublime_text/sublime_text
    desktop: sublime_text/sublime_text.desktop

parts:
  sublime-text:
    plugin: nil
    override-build: |
      snapcraftctl build
      # Get the latest release
      echo "Get latest release..."
      VERSION=$(curl -s https://download.sublimetext.com/latest/stable)
      snapcraftctl set-version $VERSION

      # Download the latest tarball
      ARCHITECTURE=$(dpkg --print-architecture)
      if [ "${ARCHITECTURE}" = "amd64" ]; then
        BUILD="x64"
      elif [ "${ARCHITECTURE}" = "i386" ]; then
        BUILD="x32"
      else
        echo "ERROR! Sublime Text tarballs are only available for amd64 and i386. Failing the build here."
        exit 1
      fi
      TARBALL_URL=https://download.sublimetext.com/sublime_text_3_build_${VERSION}_${BUILD}.tar.bz2
      echo "Downloading ${TARBALL_URL}..."
      wget -q -O- "${TARBALL_URL}" | tar jxf - -C "${SNAPCRAFT_PART_INSTALL}"

      # Correct the extraction path so it matches assets held within.
      mv "${SNAPCRAFT_PART_INSTALL}/sublime_text_3" "${SNAPCRAFT_PART_INSTALL}/sublime_text"

      # Correct icon path
      sed -i 's|Icon=sublime-text|Icon=/sublime_text/Icon/256x256/sublime-text.png|' $SNAPCRAFT_PART_INSTALL/sublime_text/sublime_text.desktop
      # Desktop Action are not Unity specific.
      sed -i 's|OnlyShowIn|#OnlyShowIn|g' $SNAPCRAFT_PART_INSTALL/sublime_text/sublime_text.desktop
    build-packages:
      - dpkg
      - sed
      - tar
      - wget
      - curl
      - bzip2
    stage-packages:
      - libbsd0
      - libffi6
      - libgtk-3-0
      - libpcre3
      - libx11-6
      - libxau6
      - libxcb1
      - libxdmcp6
    build-attributes:
      - no-patchelf
